
export const GAMEBOARD_GENERATE_TILES = 'GAMEBOARD_GENERATE_TILES';
export const GAMEBOARD_GENERATE_LADDERS = 'GAMEBOARD_GENERATE_LADDERS';
export const GAMEBOARD_GENERATE_SNAKES = 'GAMEBOARD_GENERATE_SNAKES';


export const PLAYER_CREATE = 'PLAYER_CREATE';
export const PLAYER_DELETE = 'PLAYER_DELETE';
export const PLAYER_DELETE_ALL = 'PLAYER_DELETE_ALL';
export const PLAYER_UPDATE_NAME = 'PLAYER_UPDATE_NAME';
export const PLAYER_UPDATE_POSITION = 'PLAYER_UPDATE_POSITION';
export const PLAYER_STATS_UPDATE = 'PLAYER_STATS_UPDATE';


export const GAME_UPDATE_PERFECT_THROWS = 'GAME_UPDATE_PERFECT_THROWS';
export const GAME_CONFIG_SET_MODE = 'GAME_CONFIG_SET_MODE';
export const GAME_CONFIG_SET_DIFFICULTY = 'GAME_CONFIG_SET_DIFFICULTY';
export const GAME_CONFIG_SET_START = 'GAME_CONFIG_SET_START';
export const GAME_CONFIG_UPDATE_DICE = 'GAME_CONFIG_UPDATE_DICE';
export const GAME_CONFIG_RESET_DICE = 'GAME_CONFIG_RESET_DICE';
export const GAME_CONFIG_RESET_DICE_SIX_COUNT = 'GAME_CONFIG_RESET_DICE_SIX_COUNT';
export const GAME_CONFIG_SET_CURRENT = 'GAME_CONFIG_SET_CURRENT';
export const GAME_CONFIG_SET_WINNER = 'GAME_CONFIG_SET_WINNER';














